<?php
			if( function_exists('acf_add_local_field_group') ):
acf_add_local_field_group(array(
	'key' => 'group_6352a4bbb1119',
	'title' => 'Senior Design 2023',
	'fields' => array(
		array(
			'key' => 'field_6352ac735d627',
			'label' => 'ACCORDING TO YOUR SPONSOR: Does your project have NDA or CUI restrictions that LIMIT what we can publish on your team’s public webpage on seniordesignday.uconn.edu?',
			'name' => 'has_nda_cui',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Yes' => 'Yes',
				'No' => 'No',
			),
			'default_value' => 'No',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6352a4bbbe85f',
			'label' => 'ACCORDING TO YOUR SPONSOR: What can we publish on your webpage? (Will be viewed by the public)',
			'name' => 'is_public',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'EVERYTHING: all webform content AND our uploaded project video' => 'EVERYTHING: all webform content AND our uploaded project video',
				'Webform content ONLY, NOT our project video' => 'Webform content ONLY, NOT our project video',
				'STRICTLY LIMITED TO: Team Photo with Team Member names, Sponsor Name (if NOT allowed enter “UConn Engineering”) and your Official Project title (or non-specific project title your sponsor has APPROVED)' => 'STRICTLY LIMITED TO: Team Photo with Team Member names, Sponsor Name (if NOT allowed enter “UConn Engineering”) and your Official Project title (or non-specific project title your sponsor has APPROVED)',
			),
			'default_value' => 'Yes',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6352a4bbbe8ae',
			'label' => 'Does your sponsor PROHIBIT you from sharing your project VIDEO publicly on the senior design website?',
			'name' => 'allow_public_video',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'yes' => 'Yes',
				'no' => 'No',
			),
			'default_value' => 'Yes',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		), 
		array(
			'key' => 'field_6352a4bbbe8f8',
			'label' => "Project Video link [DO NOT USE THIS FIELD FOR YOU VIDEO, USE THE \"<b>Kaltura Video Embed Code</b>\" box below]",
			'name' => 'youtube_video',
			'type' => 'url',
			'instructions' => 'do not use this box for the video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		
array(
			'key' => 'field_643559e839cc3',
			'label' => 'Kaltura Video Embed Code',
			'name' => 'kaltura_video',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		
		array(
			'key' => 'field_6352a4bbbe942',
			'label' => 'Upload your official team photo',
			'name' => 'team_photo',
			'type' => 'image',
			'instructions' => 'please upload a high resolution photo',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_6352a4bbbe98c',
			'label' => 'Sponsor Logo',
			'name' => 'sponsor_logo',
			'type' => 'image',
			'instructions' => 'if available, please include a high resolution photo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_6352a4bbbe9d5',
			'label' => 'Figure One',
			'name' => 'figure_one',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_6352a4bbbea1e',
			'label' => 'Figure Two',
			'name' => 'figure_two',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_6352a4bbbeac9',
			'label' => 'Team Number',
			'name' => 'team_number',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_6352a4bbbeb1b',
			'label' => 'Faculty Advisor',
			'name' => 'faculty_advisor',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6352a4bbbeb65',
			'label' => 'Is your team working on your senior design project with a team from another engineering department?',
			'name' => 'is_multiple_teams',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'no' => 'No',
				'yes' => 'Yes',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6352a4bbbebb9',
			'label' => 'If yes, select all of the other teams from this list',
			'name' => 'multiple_other_teams_list',
			'type' => 'select',
			'instructions' => 'to select multiple teams: mac users, hold CMD the button and click on the teams; pc users, hold the CNTRL button and click on the teams',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Biomedical Engineering 1' => 'Biomedical Engineering 1',
				'Biomedical Engineering 2' => 'Biomedical Engineering 2',
				'Biomedical Engineering 3' => 'Biomedical Engineering 3',
				'Biomedical Engineering 4' => 'Biomedical Engineering 4',
				'Biomedical Engineering 5' => 'Biomedical Engineering 5',
				'Biomedical Engineering 6' => 'Biomedical Engineering 6',
				'Biomedical Engineering 7' => 'Biomedical Engineering 7',
				'Biomedical Engineering 8' => 'Biomedical Engineering 8',
				'Biomedical Engineering 9' => 'Biomedical Engineering 9',
				'Biomedical Engineering 10' => 'Biomedical Engineering 10',
				'Biomedical Engineering 11' => 'Biomedical Engineering 11',
				'Biomedical Engineering 12' => 'Biomedical Engineering 12',
				'Biomedical Engineering 13' => 'Biomedical Engineering 13',
				'Biomedical Engineering 14' => 'Biomedical Engineering 14',
				'Biomedical Engineering 15' => 'Biomedical Engineering 15',
				'Biomedical Engineering 16' => 'Biomedical Engineering 16',
				'Biomedical Engineering 17' => 'Biomedical Engineering 17',
				'Biomedical Engineering 18' => 'Biomedical Engineering 18',
				'Biomedical Engineering 19' => 'Biomedical Engineering 19',
				'Biomedical Engineering 20' => 'Biomedical Engineering 20',
				'Biomedical Engineering 21' => 'Biomedical Engineering 21',
				'Chemical and Biomolecular Engineering 1' => 'Chemical and Biomolecular Engineering 1',
				'Chemical and Biomolecular Engineering 2' => 'Chemical and Biomolecular Engineering 2',
				'Chemical and Biomolecular Engineering 3' => 'Chemical and Biomolecular Engineering 3',
				'Chemical and Biomolecular Engineering 4' => 'Chemical and Biomolecular Engineering 4',
				'Chemical and Biomolecular Engineering 5' => 'Chemical and Biomolecular Engineering 5',
				'Chemical and Biomolecular Engineering 6' => 'Chemical and Biomolecular Engineering 6',
				'Chemical and Biomolecular Engineering 7' => 'Chemical and Biomolecular Engineering 7',
				'Chemical and Biomolecular Engineering 8' => 'Chemical and Biomolecular Engineering 8',
				'Chemical and Biomolecular Engineering 9' => 'Chemical and Biomolecular Engineering 9',
				'Chemical and Biomolecular Engineering 10' => 'Chemical and Biomolecular Engineering 10',
				'Chemical and Biomolecular Engineering 11' => 'Chemical and Biomolecular Engineering 11',
				'Chemical and Biomolecular Engineering 12' => 'Chemical and Biomolecular Engineering 12',
				'Chemical and Biomolecular Engineering 13' => 'Chemical and Biomolecular Engineering 13',
				'Chemical and Biomolecular Engineering 14' => 'Chemical and Biomolecular Engineering 14',
				'Chemical and Biomolecular Engineering 15' => 'Chemical and Biomolecular Engineering 15',
				'Chemical and Biomolecular Engineering 16' => 'Chemical and Biomolecular Engineering 16',
				'Chemical and Biomolecular Engineering 17' => 'Chemical and Biomolecular Engineering 17',
				'Chemical and Biomolecular Engineering 18' => 'Chemical and Biomolecular Engineering 18',
				'Chemical and Biomolecular Engineering 19' => 'Chemical and Biomolecular Engineering 19',
				'Chemical and Biomolecular Engineering 20' => 'Chemical and Biomolecular Engineering 20',
				'Chemical and Biomolecular Engineering 21' => 'Chemical and Biomolecular Engineering 21',
				'Chemical and Biomolecular Engineering 22' => 'Chemical and Biomolecular Engineering 22',
				'Chemical and Biomolecular Engineering 23' => 'Chemical and Biomolecular Engineering 23',
				'Civil and Environmental Engineering 1' => 'Civil and Environmental Engineering 1',
				'Civil and Environmental Engineering 2' => 'Civil and Environmental Engineering 2',
				'Civil and Environmental Engineering 3' => 'Civil and Environmental Engineering 3',
				'Civil and Environmental Engineering 4' => 'Civil and Environmental Engineering 4',
				'Civil and Environmental Engineering 5' => 'Civil and Environmental Engineering 5',
				'Civil and Environmental Engineering 6' => 'Civil and Environmental Engineering 6',
				'Civil and Environmental Engineering 7' => 'Civil and Environmental Engineering 7',
				'Civil and Environmental Engineering 8' => 'Civil and Environmental Engineering 8',
				'Civil and Environmental Engineering 9' => 'Civil and Environmental Engineering 9',
				'Civil and Environmental Engineering 10' => 'Civil and Environmental Engineering 10',
				'Civil and Environmental Engineering 11' => 'Civil and Environmental Engineering 11',
				'Civil and Environmental Engineering 12' => 'Civil and Environmental Engineering 12',
				'Civil and Environmental Engineering 13' => 'Civil and Environmental Engineering 13',
				'Civil and Environmental Engineering 14' => 'Civil and Environmental Engineering 14',
				'Civil and Environmental Engineering 15' => 'Civil and Environmental Engineering 15',
				'Civil and Environmental Engineering 16' => 'Civil and Environmental Engineering 16',
				'Civil and Environmental Engineering 17' => 'Civil and Environmental Engineering 17',
				'Civil and Environmental Engineering 18' => 'Civil and Environmental Engineering 18',
				'Civil and Environmental Engineering 19' => 'Civil and Environmental Engineering 19',
				'Civil and Environmental Engineering 20' => 'Civil and Environmental Engineering 20',
				'Civil and Environmental Engineering 21' => 'Civil and Environmental Engineering 21',
				'Environmental Engineering	1' => 'Environmental Engineering	1',
				'Environmental Engineering	2' => 'Environmental Engineering	2',
				'Environmental Engineering	3' => 'Environmental Engineering	3',
				'Environmental Engineering	4' => 'Environmental Engineering	4',
				'Environmental Engineering	5' => 'Environmental Engineering	5',
				'Environmental Engineering	6' => 'Environmental Engineering	6',
				'Environmental Engineering	7' => 'Environmental Engineering	7',
				'Environmental Engineering	8' => 'Environmental Engineering	8',
				'Environmental Engineering	9' => 'Environmental Engineering	9',
				'Computer Science & Engineering 1' => 'Computer Science & Engineering 1',
				'Computer Science & Engineering 2' => 'Computer Science & Engineering 2',
				'Computer Science & Engineering 3' => 'Computer Science & Engineering 3',
				'Computer Science & Engineering 4' => 'Computer Science & Engineering 4',
				'Computer Science & Engineering 5' => 'Computer Science & Engineering 5',
				'Computer Science & Engineering 6' => 'Computer Science & Engineering 6',
				'Computer Science & Engineering 7' => 'Computer Science & Engineering 7',
				'Computer Science & Engineering 8' => 'Computer Science & Engineering 8',
				'Computer Science & Engineering 9' => 'Computer Science & Engineering 9',
				'Computer Science & Engineering 10' => 'Computer Science & Engineering 10',
				'Computer Science & Engineering 11' => 'Computer Science & Engineering 11',
				'Computer Science & Engineering 12' => 'Computer Science & Engineering 12',
				'Computer Science & Engineering 13' => 'Computer Science & Engineering 13',
				'Computer Science & Engineering 14' => 'Computer Science & Engineering 14',
				'Computer Science & Engineering 15' => 'Computer Science & Engineering 15',
				'Computer Science & Engineering 16' => 'Computer Science & Engineering 16',
				'Computer Science & Engineering 17' => 'Computer Science & Engineering 17',
				'Computer Science & Engineering 18' => 'Computer Science & Engineering 18',
				'Computer Science & Engineering 19' => 'Computer Science & Engineering 19',
				'Computer Science & Engineering 20' => 'Computer Science & Engineering 20',
				'Computer Science & Engineering 21' => 'Computer Science & Engineering 21',
				'Computer Science & Engineering 22' => 'Computer Science & Engineering 22',
				'Computer Science & Engineering 23' => 'Computer Science & Engineering 23',
				'Computer Science & Engineering 24' => 'Computer Science & Engineering 24',
				'Computer Science & Engineering 25' => 'Computer Science & Engineering 25',
				'Computer Science & Engineering 26' => 'Computer Science & Engineering 26',
				'Computer Science & Engineering 27' => 'Computer Science & Engineering 27',
				'Computer Science & Engineering 28' => 'Computer Science & Engineering 28',
				'Computer Science & Engineering 29' => 'Computer Science & Engineering 29',
				'Computer Science & Engineering 30' => 'Computer Science & Engineering 30',
				'Computer Science & Engineering 31' => 'Computer Science & Engineering 31',
				'Computer Science & Engineering 32' => 'Computer Science & Engineering 32',
				'Computer Science & Engineering 33' => 'Computer Science & Engineering 33',
				'Computer Science & Engineering 34' => 'Computer Science & Engineering 34',
				'Computer Science & Engineering 35' => 'Computer Science & Engineering 35',
				'Computer Science & Engineering 36' => 'Computer Science & Engineering 36',
				'Computer Science & Engineering 37' => 'Computer Science & Engineering 37',
				'Computer Science & Engineering 38' => 'Computer Science & Engineering 38',
				'Computer Science & Engineering 39' => 'Computer Science & Engineering 39',
				'Computer Science & Engineering 40' => 'Computer Science & Engineering 40',
				'Computer Science & Engineering 41' => 'Computer Science & Engineering 41',
				'Computer Science & Engineering 42' => 'Computer Science & Engineering 42',
				'Electrical and Computer Engineering 1' => 'Electrical and Computer Engineering 1',
				'Electrical and Computer Engineering 2' => 'Electrical and Computer Engineering 2',
				'Electrical and Computer Engineering 3' => 'Electrical and Computer Engineering 3',
				'Electrical and Computer Engineering 4' => 'Electrical and Computer Engineering 4',
				'Electrical and Computer Engineering 5' => 'Electrical and Computer Engineering 5',
				'Electrical and Computer Engineering 6' => 'Electrical and Computer Engineering 6',
				'Electrical and Computer Engineering 7' => 'Electrical and Computer Engineering 7',
				'Electrical and Computer Engineering 8' => 'Electrical and Computer Engineering 8',
				'Electrical and Computer Engineering 9' => 'Electrical and Computer Engineering 9',
				'Electrical and Computer Engineering 10' => 'Electrical and Computer Engineering 10',
				'Electrical and Computer Engineering 11' => 'Electrical and Computer Engineering 11',
				'Electrical and Computer Engineering 12' => 'Electrical and Computer Engineering 12',
				'Electrical and Computer Engineering 13' => 'Electrical and Computer Engineering 13',
				'Electrical and Computer Engineering 14' => 'Electrical and Computer Engineering 14',
				'Electrical and Computer Engineering 15' => 'Electrical and Computer Engineering 15',
				'Electrical and Computer Engineering 16' => 'Electrical and Computer Engineering 16',
				'Electrical and Computer Engineering 17' => 'Electrical and Computer Engineering 17',
				'Electrical and Computer Engineering 18' => 'Electrical and Computer Engineering 18',
				'Electrical and Computer Engineering 19' => 'Electrical and Computer Engineering 19',
				'Electrical and Computer Engineering 20' => 'Electrical and Computer Engineering 20',
				'Electrical and Computer Engineering 21' => 'Electrical and Computer Engineering 21',
				'Electrical and Computer Engineering 22' => 'Electrical and Computer Engineering 22',
				'Electrical and Computer Engineering 23' => 'Electrical and Computer Engineering 23',
				'Electrical and Computer Engineering 24' => 'Electrical and Computer Engineering 24',
				'Electrical and Computer Engineering 25' => 'Electrical and Computer Engineering 25',
				'Electrical and Computer Engineering 26' => 'Electrical and Computer Engineering 26',
				'Electrical and Computer Engineering 27' => 'Electrical and Computer Engineering 27',
				'Electrical and Computer Engineering 28' => 'Electrical and Computer Engineering 28',
				'Electrical and Computer Engineering 29' => 'Electrical and Computer Engineering 29',
				'Electrical and Computer Engineering 30' => 'Electrical and Computer Engineering 30',
				'Management & Engineering for Manufacturing 1' => 'Management & Engineering for Manufacturing 1',
				'Management & Engineering for Manufacturing 2' => 'Management & Engineering for Manufacturing 2',
				'Management & Engineering for Manufacturing 3' => 'Management & Engineering for Manufacturing 3',
				'Management & Engineering for Manufacturing 4' => 'Management & Engineering for Manufacturing 4',
				'Management & Engineering for Manufacturing 5' => 'Management & Engineering for Manufacturing 5',
				'Management & Engineering for Manufacturing 6' => 'Management & Engineering for Manufacturing 6',
				'Management & Engineering for Manufacturing 7' => 'Management & Engineering for Manufacturing 7',
				'Management & Engineering for Manufacturing 8' => 'Management & Engineering for Manufacturing 8',
				'Management & Engineering for Manufacturing 9' => 'Management & Engineering for Manufacturing 9',
				'Management & Engineering for Manufacturing 10' => 'Management & Engineering for Manufacturing 10',
				'Management & Engineering for Manufacturing 11' => 'Management & Engineering for Manufacturing 11',
				'Management & Engineering for Manufacturing 12' => 'Management & Engineering for Manufacturing 12',
				'Management & Engineering for Manufacturing 13' => 'Management & Engineering for Manufacturing 13',
				'Management & Engineering for Manufacturing 14' => 'Management & Engineering for Manufacturing 14',
				'Management & Engineering for Manufacturing 15' => 'Management & Engineering for Manufacturing 15',
				'Management & Engineering for Manufacturing 16' => 'Management & Engineering for Manufacturing 16',
				'Management & Engineering for Manufacturing 17' => 'Management & Engineering for Manufacturing 17',
				'Management & Engineering for Manufacturing 18' => 'Management & Engineering for Manufacturing 18',
				'Management & Engineering for Manufacturing 19' => 'Management & Engineering for Manufacturing 19',
				'Management & Engineering for Manufacturing 20' => 'Management & Engineering for Manufacturing 20',
				'Materials Science & Engineering 1' => 'Materials Science & Engineering 1',
				'Materials Science & Engineering 2' => 'Materials Science & Engineering 2',
				'Materials Science & Engineering 3' => 'Materials Science & Engineering 3',
				'Materials Science & Engineering 4' => 'Materials Science & Engineering 4',
				'Materials Science & Engineering 5' => 'Materials Science & Engineering 5',
				'Materials Science & Engineering 6' => 'Materials Science & Engineering 6',
				'Materials Science & Engineering 7' => 'Materials Science & Engineering 7',
				'Materials Science & Engineering 8' => 'Materials Science & Engineering 8',
				'Materials Science & Engineering 9' => 'Materials Science & Engineering 9',
				'Mechanical Engineering 1' => 'Mechanical Engineering 1',
				'Mechanical Engineering 2' => 'Mechanical Engineering 2',
				'Mechanical Engineering 3' => 'Mechanical Engineering 3',
				'Mechanical Engineering 4' => 'Mechanical Engineering 4',
				'Mechanical Engineering 5' => 'Mechanical Engineering 5',
				'Mechanical Engineering 7' => 'Mechanical Engineering 7',
				'Mechanical Engineering 8' => 'Mechanical Engineering 8',
				'Mechanical Engineering 9' => 'Mechanical Engineering 9',
				'Mechanical Engineering 10' => 'Mechanical Engineering 10',
				'Mechanical Engineering 11' => 'Mechanical Engineering 11',
				'Mechanical Engineering 12' => 'Mechanical Engineering 12',
				'Mechanical Engineering 13' => 'Mechanical Engineering 13',
				'Mechanical Engineering 14' => 'Mechanical Engineering 14',
				'Mechanical Engineering 15' => 'Mechanical Engineering 15',
				'Mechanical Engineering 16' => 'Mechanical Engineering 16',
				'Mechanical Engineering 17' => 'Mechanical Engineering 17',
				'Mechanical Engineering 18' => 'Mechanical Engineering 18',
				'Mechanical Engineering 19' => 'Mechanical Engineering 19',
				'Mechanical Engineering 20' => 'Mechanical Engineering 20',
				'Mechanical Engineering 21' => 'Mechanical Engineering 21',
				'Mechanical Engineering 22' => 'Mechanical Engineering 22',
				'Mechanical Engineering 23' => 'Mechanical Engineering 23',
				'Mechanical Engineering 24' => 'Mechanical Engineering 24',
				'Mechanical Engineering 25' => 'Mechanical Engineering 25',
				'Mechanical Engineering 26' => 'Mechanical Engineering 26',
				'Mechanical Engineering 27' => 'Mechanical Engineering 27',
				'Mechanical Engineering 28' => 'Mechanical Engineering 28',
				'Mechanical Engineering 29' => 'Mechanical Engineering 29',
				'Mechanical Engineering 30' => 'Mechanical Engineering 30',
				'Mechanical Engineering 31' => 'Mechanical Engineering 31',
				'Mechanical Engineering 32' => 'Mechanical Engineering 32',
				'Mechanical Engineering 33' => 'Mechanical Engineering 33',
				'Mechanical Engineering 34' => 'Mechanical Engineering 34',
				'Mechanical Engineering 35' => 'Mechanical Engineering 35',
				'Mechanical Engineering 36' => 'Mechanical Engineering 36',
				'Mechanical Engineering 37' => 'Mechanical Engineering 37',
				'Mechanical Engineering 38' => 'Mechanical Engineering 38',
				'Mechanical Engineering 39' => 'Mechanical Engineering 39',
				'Mechanical Engineering 40' => 'Mechanical Engineering 40',
				'Mechanical Engineering 41' => 'Mechanical Engineering 41',
				'Mechanical Engineering 42' => 'Mechanical Engineering 42',
				'Mechanical Engineering 43' => 'Mechanical Engineering 43',
				'Mechanical Engineering 44' => 'Mechanical Engineering 44',
				'Mechanical Engineering 45' => 'Mechanical Engineering 45',
				'Mechanical Engineering 46' => 'Mechanical Engineering 46',
				'Mechanical Engineering 47' => 'Mechanical Engineering 47',
				'Mechanical Engineering 48' => 'Mechanical Engineering 48',
				'Mechanical Engineering 49' => 'Mechanical Engineering 49',
				'Mechanical Engineering 50' => 'Mechanical Engineering 50',
				'Mechanical Engineering 51' => 'Mechanical Engineering 51',
				'Mechanical Engineering 52' => 'Mechanical Engineering 52',
				'Mechanical Engineering 53' => 'Mechanical Engineering 53',
				'Mechanical Engineering 54' => 'Mechanical Engineering 54',
				'Mechanical Engineering 56' => 'Mechanical Engineering 56',
				'Mechanical Engineering 57' => 'Mechanical Engineering 57',
				'Mechanical Engineering 58' => 'Mechanical Engineering 58',
				'Mechanical Engineering 59' => 'Mechanical Engineering 59',
				'Mechanical Engineering 60' => 'Mechanical Engineering 60',
				'Mechanical Engineering 62' => 'Mechanical Engineering 62',
				'Mechanical Engineering 63' => 'Mechanical Engineering 63',
				'Mechanical Engineering 64' => 'Mechanical Engineering 64',
				'Mechanical Engineering 65' => 'Mechanical Engineering 65',
				'Mechanical Engineering 66' => 'Mechanical Engineering 66',
				'Mechanical Engineering 67' => 'Mechanical Engineering 67',
				'Mechanical Engineering 68' => 'Mechanical Engineering 68',
				'Mechanical Engineering 69' => 'Mechanical Engineering 69',
				'Mechanical Engineering 70' => 'Mechanical Engineering 70',
				'Mechanical Engineering 71' => 'Mechanical Engineering 71',
				'Mechanical Engineering 72' => 'Mechanical Engineering 72',
				'Mechanical Engineering 73' => 'Mechanical Engineering 73',
				'Mechanical Engineering 74' => 'Mechanical Engineering 74',
				'Mechanical Engineering 75' => 'Mechanical Engineering 75',
				'Mechanical Engineering 76' => 'Mechanical Engineering 76',
				'Mechanical Engineering 77' => 'Mechanical Engineering 77',
				'Mechanical Engineering 78' => 'Mechanical Engineering 78',
				'Mechanical Engineering 79' => 'Mechanical Engineering 79',
				'Mechanical Engineering 80' => 'Mechanical Engineering 80',
				'Mechanical Engineering 81' => 'Mechanical Engineering 81',
				'Mechanical Engineering 82' => 'Mechanical Engineering 82',
				'Mechanical Engineering 83' => 'Mechanical Engineering 83',
				'Mechanical Engineering 84' => 'Mechanical Engineering 84',
				'Mechanical Engineering 85' => 'Mechanical Engineering 85',
				'Mechanical Engineering 86' => 'Mechanical Engineering 86',
				'Mechanical Engineering 87' => 'Mechanical Engineering 87',
				'Mechanical Engineering 88' => 'Mechanical Engineering 88',
				'Systems Engineering 1' => 'Systems Engineering 1',
				'Systems Engineering 2' => 'Systems Engineering 2',
				'Systems Engineering 3' => 'Systems Engineering 3',
				'Systems Engineering 4' => 'Systems Engineering 4',
				'Systems Engineering 5' => 'Systems Engineering 5',
				'Systems Engineering 6' => 'Systems Engineering 6',
				'Systems Engineering 7' => 'Systems Engineering 7',
				'Systems Engineering 8' => 'Systems Engineering 8',
				'Systems Engineering 9' => 'Systems Engineering 9',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 1,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6352a4bbbec07',
			'label' => 'Sponsor',
			'name' => 'sponsor',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
'sponsor not indicated by team' => 'sponsor not indicated by team',
'ABB' => 'ABB',
'Acc Masters' => 'Acc Masters',
'Acme' => 'Acme',
'ACMT, Inc.' => 'ACMT, Inc.',
'AECOM' => 'AECOM',
'Aerogear' => 'Aerogear',
'Agrivolution LLC' => 'Agrivolution LLC',
'AI-Tek Instruments' => 'AI-Tek Instruments',
'Airbornway' => 'Airbornway',
'American Society of Naval Engineers' => 'American Society of Naval Engineers',
'Aquiline Drones' => 'Aquiline Drones',
'ARKA' => 'ARKA',
'AromaKIT - Dr. Ransome' => 'AromaKIT - Dr. Ransome',
'ASML' => 'ASML',
'ASSA ABLOY' => 'ASSA ABLOY',
'Associated Spring' => 'Associated Spring',
'Atlas Stamping & Manufacturing' => 'Atlas Stamping & Manufacturing',
'AtlasXomics' => 'AtlasXomics',
'Avitus Orthopaedics, Inc.' => 'Avitus Orthopaedics, Inc.',
'Barnes Aerospace' => 'Barnes Aerospace',
'Bauer Inc.' => 'Bauer Inc.',
'Bee and Thistle Inn -- Dave Rufo & Tosh Urbowicz' => 'Bee and Thistle Inn -- Dave Rufo & Tosh Urbowicz',
'Belimo Americas' => 'Belimo Americas',
'Beta Shim' => 'Beta Shim',
'Biomass Controls' => 'Biomass Controls',
'BioMass' => 'BioMass',
'Biorasis' => 'Biorasis',
'Blue Crest' => 'Blue Crest',
'Boehringer Ingelheim' => 'Boehringer Ingelheim',
'Branson Ultrasonics' => 'Branson Ultrasonics',
'BYK USA Inc' => 'BYK USA Inc',
'Cabot Corporation' => 'Cabot Corporation',
'Cadence, Inc.' => 'Cadence, Inc.',
'Cadenza Innovation, Inc.' => 'Cadenza Innovation, Inc.',
'Candoo' => 'Candoo',
'Cannon' => 'Cannon',
'Carlyle Johnson' => 'Carlyle Johnson',
'Center for Clean Energy Engineering (C2E2)' => 'Center for Clean Energy Engineering (C2E2)',
'Center for Ecological Study of Perception and Action (CESPA)' => 'Center for Ecological Study of Perception and Action (CESPA)',
'Central Wire Industries' => 'Central Wire Industries',
'CGI' => 'CGI',
'CHA Consulting, Inc.' => 'CHA Consulting, Inc.',
'Chapman Manufacturing' => 'Chapman Manufacturing',
'Charles Gray Airboat' => 'Charles Gray Airboat',
'Charter Oak Environmental Services' => 'Charter Oak Environmental Services',
'Cigna' => 'Cigna',
'City of Hartford, Keney Memorial Clock Tower' => 'City of Hartford, Keney Memorial Clock Tower',
'CME Associates' => 'CME Associates',
'CMS' => 'CMS',
'Coast Guard Academy' => 'Coast Guard Academy',
'Cognizant Technology Solutions' => 'Cognizant Technology Solutions',
'Collins Aerospace' => 'Collins Aerospace',
'Colonial Bronze Co.' => 'Colonial Bronze Co.',
'Comprehensive Environmental, Inc.' => 'Comprehensive Environmental, Inc.',
'Computational Materials and Mechanics Group (CMMG)' => 'Computational Materials and Mechanics Group (CMMG)',
'Conlon Engineering' => 'Conlon Engineering',
'Connecticut Air National Guard (CTANG)' => 'Connecticut Air National Guard (CTANG)',
'Connecticut Center for Advanced Technology, Inc. (CCAT)' => 'Connecticut Center for Advanced Technology, Inc. (CCAT)',
'Connecticut Children\'s Medical Center (CCMC)' => 'Connecticut Children\'s Medical Center (CCMC)',
'Connecticut Department of Energy and Environmental Protection (CT DEEP)' => 'Connecticut Department of Energy and Environmental Protection (CT DEEP)',
'Connecticut Department of Transportation (CTDOT)' => 'Connecticut Department of Transportation (CTDOT)',
'Convention Nation' => 'Convention Nation',
'Creative Conners, Inc.' => 'Creative Conners, Inc.',
'Creative Conners' => 'Creative Conners',
'CTI' => 'CTI',
'CTNG' => 'CTNG',
'De-Simone Consulting' => 'De-Simone Consulting',
'Denison Homestead' => 'Denison Homestead',
'Department of Public Works, City of Hartford' => 'Department of Public Works, City of Hartford',
'Diameter Health' => 'Diameter Health',
'DigiPops' => 'DigiPops',
'Dive' => 'Dive',
'Dr. Kristen Morgan' => 'Dr. Kristen Morgan',
'Dr. Martin Han' => 'Dr. Martin Han',
'Dr. Syam Nukavarapu' => 'Dr. Syam Nukavarapu',
'Dr.Ransome' => 'Dr.Ransome',
'Draper Laboratory' => 'Draper Laboratory',
'Dyadic Innovations' => 'Dyadic Innovations',
'Dymax' => 'Dymax',
'EA Patten' => 'EA Patten',
'EDAC Technologies' => 'EDAC Technologies',
'Energid' => 'Energid',
'Ensign-Bickford Aerospace & Defense' => 'Ensign-Bickford Aerospace & Defense',
'Eversource' => 'Eversource',
'FM Global' => 'FM Global',
'Fuss & O\'Neill' => 'Fuss & O\'Neill',
'Gems Sensors & Controls' => 'Gems Sensors & Controls',
'General Dynamics Electric Boat' => 'General Dynamics Electric Boat',
'GKN Aerospace' => 'GKN Aerospace',
'GM2 Associates' => 'GM2 Associates',
'Great Hammock Beach Association' => 'Great Hammock Beach Association',
'Greaves' => 'Greaves',
'Greenwich Energy Solutions' => 'Greenwich Energy Solutions',
'Guillotine' => 'Guillotine',
'Hamilton College' => 'Hamilton College',
'HarcoSemco' => 'HarcoSemco',
'Hartford Business Improvement District and the iQuilt Partnership' => 'Hartford Business Improvement District and the iQuilt Partnership',
'Hartford HealthCare Rehabilitation Network' => 'Hartford HealthCare Rehabilitation Network',
'HDR, Inc.' => 'HDR, Inc.',
'HNTB Corporation' => 'HNTB Corporation',
'Holo Krome' => 'Holo Krome',
'Hologic, Inc.' => 'Hologic, Inc.',
'Hongyi Xu' => 'Hongyi Xu',
'HORST Engineering' => 'HORST Engineering',
'HORST Engineering' => 'HORST Engineering',
'Hoshino Lab' => 'Hoshino Lab',
'HSB' => 'HSB',
'Hubbell Incorporated' => 'Hubbell Incorporated',
'HyAxiom' => 'HyAxiom',
'HyAxiom' => 'HyAxiom',
'ID Mial Systems' => 'ID Mial Systems',
'Innovation Cooperative 3D (IC3D)' => 'Innovation Cooperative 3D (IC3D)',
'Institute for Collaboration on Health, Intervention, and Policy (InCHIP)' => 'Institute for Collaboration on Health, Intervention, and Policy (InCHIP)',
'Interface Technologies' => 'Interface Technologies',
'ISO-NE' => 'ISO-NE',
'Jacobs Vehicle Systems' => 'Jacobs Vehicle Systems',
'JKMuir' => 'JKMuir',
'Johnson & Johnson, DePuy Synthes' => 'Johnson & Johnson, DePuy Synthes',
'Joshua\'s Trust' => 'Joshua\'s Trust',
'Keney Park Sustainability Project' => 'Keney Park Sustainability Project',
'Kimley-Horn' => 'Kimley-Horn',
'Kinsley Power Systems' => 'Kinsley Power Systems',
'Kleinfelder' => 'Kleinfelder',
'Kolb' => 'Kolb',
'KX Technologies' => 'KX Technologies',
'L&T Info Tech (LTI)' => 'L&T Info Tech (LTI)',
'Lambda Vision' => 'Lambda Vision',
'LeftyEQ' => 'LeftyEQ',
'Lenard Engineering, Inc.' => 'Lenard Engineering, Inc.',
'Lenze Americas' => 'Lenze Americas',
'Lochner' => 'Lochner',
'Lochner' => 'Lochner',
'Lockheed Martin' => 'Lockheed Martin',
'Logicbroker' => 'Logicbroker',
'Loureiro' => 'Loureiro',
'Manafort Brothers' => 'Manafort Brothers',
'Manchester Land Trust' => 'Manchester Land Trust',
'Marmon Comtran' => 'Marmon Comtran',
'Mattern Construction Inc.' => 'Mattern Construction Inc.',
'Mattershift' => 'Mattershift',
'Medtronic' => 'Medtronic',
'Michael Curtis' => 'Michael Curtis',
'Mitsubishi Electric Research Laboratories' => 'Mitsubishi Electric Research Laboratories',
'Mohawk NE' => 'Mohawk NE',
'MOOG Inc.' => 'MOOG Inc.',
'Movia Robotics' => 'Movia Robotics',
'Nassau Re' => 'Nassau Re',
'National Aeronautics and Space Administration (NASA)' => 'National Aeronautics and Space Administration (NASA)',
'National Guard' => 'National Guard',
'Naval Submarine Medical Research Laboratory, Lt. Dr. Beardslee' => 'Naval Submarine Medical Research Laboratory, Lt. Dr. Beardslee',
'NEC Labs America' => 'NEC Labs America',
'Nel Hydrogen' => 'Nel Hydrogen',
'NIUVT' => 'NIUVT',
'NIUVT' => 'NIUVT',
'NUWC' => 'NUWC',
'OEM Controls' => 'OEM Controls',
'Office of Naval Research' => 'Office of Naval Research',
'OMG Inc.' => 'OMG Inc.',
'Otis Elevator Company' => 'Otis Elevator Company',
'Outreach Reality Services' => 'Outreach Reality Services',
'PepsiCo Frito-Lay' => 'PepsiCo Frito-Lay',
'Pfizer' => 'Pfizer',
'Physical Sciences Inc., UCONN School of Pharmacy' => 'Physical Sciences Inc., UCONN School of Pharmacy',
'Pitney Bowes' => 'Pitney Bowes',
'POWWR' => 'POWWR',
'Pratt & Whitney - Puerto Rico' => 'Pratt & Whitney - Puerto Rico',
'Pratt & Whitney Institute for Advanced Systems Engineering' => 'Pratt & Whitney Institute for Advanced Systems Engineering',
'Pratt & Whitney' => 'Pratt & Whitney',
'Precision Combustion Inc.' => 'Precision Combustion Inc.',
'Prime AE' => 'Prime AE',
'Prof. Caiwen Ding' => 'Prof. Caiwen Ding',
'ProperGolf' => 'ProperGolf',
'Proton OnSite' => 'Proton OnSite',
'Prysmian Group' => 'Prysmian Group',
'Prysmian' => 'Prysmian',
'PTA Plastics' => 'PTA Plastics',
'Qualtech Systems' => 'Qualtech Systems',
'Quantum Biopower' => 'Quantum Biopower',
'Radio Frequency Systems' => 'Radio Frequency Systems',
'Raven Industries, Inc' => 'Raven Industries, Inc',
'Raytheon Technologies Research Center' => 'Raytheon Technologies Research Center',
'RBC Aircraft Products Inc.' => 'RBC Aircraft Products Inc.',
'REA Resource Recovery' => 'REA Resource Recovery',
'Reality Interactive' => 'Reality Interactive',
'Reverge Anslemo' => 'Reverge Anslemo',
'Richard Davids' => 'Richard Davids',
'Roller Bearing Corp' => 'Roller Bearing Corp',
'Rowheels Inc., Numotion' => 'Rowheels Inc., Numotion',
'RSCC Wire and Cable' => 'RSCC Wire and Cable',
'Rubber Labels' => 'Rubber Labels',
'SedMed' => 'SedMed',
'SedMed' => 'SedMed',
'SESI Consulting Engineers' => 'SESI Consulting Engineers',
'Sikorsky Aircraft Corporation' => 'Sikorsky Aircraft Corporation',
'Simvize LLC' => 'Simvize LLC',
'Slam Collaborative' => 'Slam Collaborative',
'Sonalysts, Inc.' => 'Sonalysts, Inc.',
'Sonalysts, Inc.' => 'Sonalysts, Inc.',
'Southern New England Industrial Assessment Center at UConn' => 'Southern New England Industrial Assessment Center at UConn',
'SPIROL' => 'SPIROL',
'Stanadyne' => 'Stanadyne',
'Stanley Access Technologies' => 'Stanley Access Technologies',
'Stanley Black & Decker' => 'Stanley Black & Decker',
'Student Affairs Information Technology' => 'Student Affairs Information Technology',
'Swagelok' => 'Swagelok',
'Synchrony Financial' => 'Synchrony Financial',
'The Carlyle Johnson Machine Company' => 'The Carlyle Johnson Machine Company',
'The Guiders Shield' => 'The Guiders Shield',
'The Jackson Laboratory' => 'The Jackson Laboratory',
'The Maritime Aquarium at Norwalk' => 'The Maritime Aquarium at Norwalk',
'The MITRE Corporation' => 'The MITRE Corporation',
'Therapeutic Bandage Products LLC' => 'Therapeutic Bandage Products LLC',
'TicketNetwork' => 'TicketNetwork',
'Tighe & Bond' => 'Tighe & Bond',
'Tout' => 'Tout',
'Town of Bolton' => 'Town of Bolton',
'Town of Essex, CT' => 'Town of Essex, CT',
'Town of Manchester, CT' => 'Town of Manchester, CT',
'Town of Mansfield, CT' => 'Town of Mansfield, CT',
'Town of Norwalk, CT' => 'Town of Norwalk, CT',
'Town of Old Lyme, CT' => 'Town of Old Lyme, CT',
'Town of Stamford, CT' => 'Town of Stamford, CT',
'Town of Stonington, CT' => 'Town of Stonington, CT',
'Town of Thompson, CT' => 'Town of Thompson, CT',
'Town of Wethersfield, CT' => 'Town of Wethersfield, CT',
'Transcend Bicycle LLC' => 'Transcend Bicycle LLC',
'Triumph Engine Control Systems' => 'Triumph Engine Control Systems',
'TRUMPF' => 'TRUMPF',
'UBTech / Movia Robotic' => 'UBTech / Movia Robotic',
'UConn Biomedical Engineering Department' => 'UConn Biomedical Engineering Department',
'UConn College of Liberal Arts and Sciences' => 'UConn College of Liberal Arts and Sciences',
'UConn College of Liberal Arts and Sciences' => 'UConn College of Liberal Arts and Sciences',
'UConn Combustion and Gas Dymanics Lab' => 'UConn Combustion and Gas Dymanics Lab',
'UConn Computational and Thermal Fluids Lab' => 'UConn Computational and Thermal Fluids Lab',
'UConn Computer Science & Engineering Department' => 'UConn Computer Science & Engineering Department',
'UConn Electric Motorsports' => 'UConn Electric Motorsports',
'UConn Electrical & Computer Engineering Department' => 'UConn Electrical & Computer Engineering Department',
'UConn Health - Dr. Kumbar Laboratory' => 'UConn Health - Dr. Kumbar Laboratory',
'UConn Health' => 'UConn Health',
'UConn IASE/Industrial Assessment Center' => 'UConn IASE/Industrial Assessment Center',
'UConn Kinesiology' => 'UConn Kinesiology',
'UConn Natural Resources/Environment' => 'UConn Natural Resources/Environment',
'UConn Power & Energy Lab' => 'UConn Power & Energy Lab',
'UConn School of Engineering' => 'UConn School of Engineering',
'UConn School of Nursing, Dr. Kyounghae Kim' => 'UConn School of Nursing, Dr. Kyounghae Kim',
'UConn School of Nursing' => 'UConn School of Nursing',
'UCONN, Dr Chiu' => 'UCONN, Dr Chiu',
'UConn, Dr. Ilies' => 'UConn, Dr. Ilies',
'UConn, Dr. Imani' => 'UConn, Dr. Imani',
'UCONN, Dr. Julian Norato' => 'UCONN, Dr. Julian Norato',
'UConn, Dr. Kim' => 'UConn, Dr. Kim',
'UCONN, Dr. Lykotrafitis' => 'UCONN, Dr. Lykotrafitis',
'UCONN, Dr. Norato' => 'UCONN, Dr. Norato',
'UCONN, Dr. Pierce' => 'UCONN, Dr. Pierce',
'UCONN, Dr. SeungYeon Kang' => 'UCONN, Dr. SeungYeon Kang',
'UCONN, Dr. Xu' => 'UCONN, Dr. Xu',
'UCONN, Dr. Zhao' => 'UCONN, Dr. Zhao',
'Ulbrich Stainless Steels & Specialty Metals' => 'Ulbrich Stainless Steels & Specialty Metals',
'Undersea Warfighting Development Center' => 'Undersea Warfighting Development Center',
'Unicorr' => 'Unicorr',
'Unilever' => 'Unilever',
'Unisoft' => 'Unisoft',
'United States Coast Guard' => 'United States Coast Guard',
'United States Navy' => 'United States Navy',
'United Technologies Aerospace Systems (UTAS)' => 'United Technologies Aerospace Systems (UTAS)',
'United Technologies Research Center (UTCRC)' => 'United Technologies Research Center (UTCRC)',
'Universal Safety Net Solution' => 'Universal Safety Net Solution',
'University of Connecticut' => 'University of Connecticut',
'University of Hartford of Rehabilitation Sciences' => 'University of Hartford of Rehabilitation Sciences',
'US Air National Guard' => 'US Air National Guard',
'US Army - Natick' => 'US Army - Natick',
'US Naval Undersea Warfare Center' => 'US Naval Undersea Warfare Center',
'UTC CCS/SCE' => 'UTC CCS/SCE',
'UTRC' => 'UTRC',
'Volo Aero MRO' => 'Volo Aero MRO',
'We-Xite Laboratory ' => 'We-Xite Laboratory ',
'Web Industries' => 'Web Industries',
'Whelen Engineering Company' => 'Whelen Engineering Company',
'Whelen Engineering' => 'Whelen Engineering',
'Whitcraft LLC' => 'Whitcraft LLC',
'WickAway' => 'WickAway',
'Willington Nameplate Inc.' => 'Willington Nameplate Inc.',
'Winchester Interconnect' => 'Winchester Interconnect',
'Windham Dental' => 'Windham Dental',
'Wright-Pierce' => 'Wright-Pierce',
'WSP' => 'WSP',
'YouCOMM LLC.' => 'YouCOMM LLC.',
'Zachry Nuclear Engineering, Inc.' => 'Zachry Nuclear Engineering, Inc.',
'ZEISS' => 'ZEISS',
				'Other' => 'Other',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6352a4bbbec54',
			'label' => 'If your sponsor was not listed, please type it here (no abbreviations allowed)',
			'name' => 'other_sponsor',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6352a4bbbec07',
						'operator' => '==',
						'value' => 'Other',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6352a4bbbeca1',
			'label' => 'Does your project have a non-UConn “Project Sponsor Advisor”?',
			'name' => 'have_a_non_uconn_project_sponsor_advisor',
			'type' => 'select',
			'instructions' => 'If the answer is no',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Yes' => 'Yes',
				'No – we ONLY have a UCONN FACULTY Advisor' => 'No – we ONLY have a UCONN FACULTY Advisor',
			),
			'default_value' => false,
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6352a4bbbecee',
			'label' => 'Non-UConn Project Sponsor Advisor',
			'name' => 'non_uconn_project_sponsor_advisor',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6352a4bbbeca1',
						'operator' => '==',
						'value' => 'Yes',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6352a4bbbed3a',
			'label' => 'Protect Title',
			'name' => 'protect_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6352a4bbbed87',
			'label' => 'Project Description',
			'name' => 'project_description',
			'type' => 'textarea',
			'instructions' => '2000 character limit, including spaces',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 2000,
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6352a4bbbedd4',
			'label' => 'Full Project Description',
			'name' => 'full_project_description',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6352c1c689ddd',
			'label' => 'Photo Note',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Please enter your teammates names in the order they appear in the photo from the left to the right.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_6352a4bbbee20',
			'label' => 'Team Member 1',
			'name' => 'team_member_1',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6352a4bbbee6c',
			'label' => 'Team Member 2',
			'name' => 'team_member_2',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6352a4bbbeeba',
			'label' => 'Team Member 3',
			'name' => 'team_member_3',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6352a4bbbef06',
			'label' => 'Team Member 4',
			'name' => 'team_member_4',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6352a4bbbef4b',
			'label' => 'Team Member 5',
			'name' => 'team_member_5',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6352a4bbbef99',
			'label' => 'Team Member 6',
			'name' => 'team_member_6',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		), /* start addition */
		array(
			'key' => 'field_65490b48d5c5f',
			'label' => 'Team Member 7',
			'name' => 'team_member_7',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_65490b4bd5c60',
			'label' => 'Team Member 8',
			'name' => 'team_member_8',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_65490b4fd5c61',
			'label' => 'Team Member 9',
			'name' => 'team_member_9',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_65490b51d5c62',
			'label' => 'Team Member 10',
			'name' => 'team_member_10',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		/* end addition */
		
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cptm',
			),
		),
		
		/*
		array(
			array(
				'param' => 'current_user_role',
				'operator' => '==',
				'value' => 'contributor',
			),
		),
		*/
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

endif;		
